"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ORDER_TYPE;
(function (ORDER_TYPE) {
    ORDER_TYPE[ORDER_TYPE["LIMIT"] = 1] = "LIMIT";
    ORDER_TYPE[ORDER_TYPE["MARKET_ORDER"] = 2] = "MARKET_ORDER";
})(ORDER_TYPE = exports.ORDER_TYPE || (exports.ORDER_TYPE = {}));
var ORDER_SIDE;
(function (ORDER_SIDE) {
    ORDER_SIDE["SHORT"] = "short";
    ORDER_SIDE["LONG"] = "long";
})(ORDER_SIDE = exports.ORDER_SIDE || (exports.ORDER_SIDE = {}));
var UI_ORDER_EVENT;
(function (UI_ORDER_EVENT) {
    UI_ORDER_EVENT["NEW_ORDER"] = "NEW_OPEN_ORDER";
    UI_ORDER_EVENT["OPEN_ORDER_CANCELLED"] = "NEW_OPEN_ORDER";
    UI_ORDER_EVENT["OPEN_ORDER_REMOVED"] = "NEW_OPEN_ORDER";
    UI_ORDER_EVENT["NEW_OPEN_POSITION"] = "NEW_OPEN_POSITION";
})(UI_ORDER_EVENT = exports.UI_ORDER_EVENT || (exports.UI_ORDER_EVENT = {}));
var OPEN_ORDER_STATUS;
(function (OPEN_ORDER_STATUS) {
    OPEN_ORDER_STATUS[OPEN_ORDER_STATUS["ACTIVE"] = 1] = "ACTIVE";
    OPEN_ORDER_STATUS[OPEN_ORDER_STATUS["COMPLETED"] = 2] = "COMPLETED";
    OPEN_ORDER_STATUS[OPEN_ORDER_STATUS["CANCELED"] = 3] = "CANCELED";
})(OPEN_ORDER_STATUS = exports.OPEN_ORDER_STATUS || (exports.OPEN_ORDER_STATUS = {}));
var OPEN_POSITION_STATUS;
(function (OPEN_POSITION_STATUS) {
    OPEN_POSITION_STATUS[OPEN_POSITION_STATUS["ACTIVE"] = 1] = "ACTIVE";
    OPEN_POSITION_STATUS[OPEN_POSITION_STATUS["COMPLETED"] = 2] = "COMPLETED";
})(OPEN_POSITION_STATUS = exports.OPEN_POSITION_STATUS || (exports.OPEN_POSITION_STATUS = {}));
//# sourceMappingURL=order.js.map